#spring
server:
  port: 8080
  servlet:
    context-path: '/api'
spring:
  application:
    name: 'accu-weather-integration-sample'
logging:
  ##file: ${project.build.directory}/logs/server.log
  level.root: INFO

#custom
accu-weather:
  api:
    apiKey:
    hostName: "http://dataservice.accuweather.com"
    version: "v1"


